### ISSUE TITLE
Add kanji to AnkiDroid

### ISSUE THREAD

**Issue by nicolas-raoul** [timrae/rikaidroid#2]
When I see a new word, I would like to add it to AnkiDroid.

**Comment by timrae** [comment]
The idea is for your dictionary to take care of that...

**Comment by timrae** [comment]
(making a high level wrapper for the AnkiDroid `ContentProvider` is my highest priority task at the moment... It will have a permissive license like LGPL or BSD, so that we can get deep support for AnkiDroid into Aedict and other dictionaries)
